### ISSUE TITLE
Failed to fetch the user profile

### ISSUE THREAD

**Issue by Rakejs** [tonestrike/passport-discord#1]
Hi,
Since the passport-discord library throwed some error like "Failed to fetch User Profile". I have changed the lib to thisone .The problem is there I still get the error.
`InternalOAuthError: Failed to fetch the user profile.
    at /home/container/passport-discord/lib/strategy.js:77:25`
Code: Example Code
Scopes: Identify,Guilds
Regards

**Comment by tonestrike** [comment]
@Rakejs can you provide the code?

**Comment by Rakejs** [comment]
The error seems like resolved .It was a redirect error. But is there any way to await fetch User guilds, Since Discord allows only to fetch user guilds every 1 sec.
Regards

**Comment by tonestrike** [comment]
@Rakejs the guilds are returned from a promise and they are only retrieved once, so there shouldn't be an issue with rate limits. This is used in heavy load production apps with no issues. Are you experiencing rate limit issues?

**Comment by Rakejs** [comment]
yeah sometimes, it happens,if many users login in same time atm it is rare. maybe 1 time in a day
Regards

**Comment by tonestrike** [comment]
@Rakejs can you send the error and the code implementation? This is installed on quite a large bot with thousands of authentication requests a day and I never once see an issue.

**Comment by Rakejs** [comment]
```

 const   fs = require("fs"),
    express = require("express"),
    strategy = require("./passport-discord").Strategy,
    session = require("express-session"),
    passport = require("passport"),
    fetch = require("node-fetch"),
let config = require("./config_second.json");

passport.serializeUser(function (user, done) {
    done(null, user);
});
passport.deserializeUser(function (obj, done) {
    done(null, obj);
});

passport.use(new strategy({
    clientID: config.client_id,
    clientSecret: config.client_secret,
    callbackURL: config.callback_url,
    scope: config.oauth_scopes
}, function (accessToken, refreshToken, profile, done) {
    process.nextTick(() => done(null, profile));
}));

app.set("view engine", "ejs");
app.use(session({
    secret: config.session_secret,
    resave: true,
    saveUninitialized: false,
    expire: 3.1709791983765E-11
}));
app.use(express.json());
app.use(passport.initialize());
app.use(passport.session());

app.use("/public", express.static("public"));

const authOnly = (req, res, next) => {
    if (req.isAuthenticated()) return next();
    else return res.redirect('/');
};

app.get("/auth/login", passport.authenticate("discord", { scope: config.oauth_scopes }), function (req, res) { });
app.get("/auth/callback", passport.authenticate("discord", { failureRedirect: "/" }), async function (req, res) {
    console.log(`[DASHBOARD] ${req.user.username} - Logging in..`);
    return res.status(200).redirect("/dashboard");
});
app.get("/auth/logout", authOnly, async (req, res) => {
    console.log(`[DASHBOARD] ${req.user.username} - Logging out..`);
    req.logout();
    res.redirect("/");
});

```
This is the error i get sometimes
```
InternalOAuthError: Failed to fetch user's guilds
    at /home/container/passport-discord/lib/strategy.js:108:32
    at passBackControl (/home/container/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/container/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by tonestrike** [comment]
@Rakejs I believe the issue might have to do with the user's themselves not giving you permission to access their guilds. I can look into this and see if I can handle this case and not through an error.

**Comment by Rakejs** [comment]
ok tysm. I will stay tuned for new updates.
